### ISSUE TITLE
PathAccessException (OS Error: Permission Denied = 13)

### ISSUE THREAD

**Issue by ghost** [ImranR98/Shoyo#3]
1. I am running Shoyo in Pixel 7A (GrapheneOS latest update as of today, Android 15).
2. I am trying to share an APK from ML Manager in a Profile via Shoyo.
3. Shoyo has full storage access permission.

But I am greeted with:

```
0 of 1 File Saved to Downloads.

[xxx].apk: PathAccessException: Cannot copy file to '/storage/emulated/0/Download/[xxx].apk',
path = '/data/user/11/dev.imranr.shoyo/cache/[xxx].apk' (OS Error: Permission Denied = 13)
```

### Steps to reproduce:

In a fresh profile,
1. Get ML Manager (Apkmirror recommended me this, when trying to upload a file) [permission Network: Disable].
2. Share any apk to Shoyo, so that it gets saved to file manager.

**Comment by Diego-Visualma** [comment]
Hello, I am having the same issue also on Graphene OS on any profile except the owner.

I can see that in line 71 of main.dart the path '/storage/emulated/0/Download' is hardcoded.

However, only the owner profile has permission to access that path. Every additional profile will have it's own storage path and will not be able to access the ones for any other profile.

The format for these paths is '/storage/emulated/[n]/Download', where n=0 for the owner profile, and n will be a number I believe greater than 10 for the others. This same number is also used in the data path, which is also unique per profile: '/data/user/[n]/dev.imranr.shoyo/cache/'.

In the case of @0x33taji , downloadsDir should point to '/storage/emulated/11/Download' because for the profile they are using, the path to their shared file in the cache is '/data/user/11/dev.imranr.shoyo/cache/[xxx].apk'.

Could it be posible to get the dirname for the file, extract the profile number which should be the third element of an array separated by '/', and use it in the downloadsDir string?

**Comment by Diego-Visualma** [comment]
I forked the project and made the fix on a new branch, but I can't test it because the repo "https://github.com/ImranR98/flutter_sharing_intent" no longer exists, and it is one of the dependencies.

Any advice?

**Comment by ImranR98** [comment]
Thanks for looking into this. We don't need my fork anymore - you can use the original package (my bugfix was merged in a PR at some point): https://github.com/bhagat-techind/flutter_sharing_intent

**Comment by Diego-Visualma** [comment]
Perfect! I went ahead and tested it on my device and it works fine in Graphene OS 15, both on the main owner profile and in the secondary profiles.

As an aside, I am a Nix user and I find it is very practical to create define development shells for each project with all necessary build dependencies, SDK versions, etc. That way it's quick and painless to launch an environment that is guaranteed to build that particular project.

Do you believe it would be useful if I made another PR with the flake.nix that I used for this build?

**Comment by ImranR98** [comment]
It would only be used by contributors who use Nix and thus risks getting out of sync with the actual dependencies the app uses. That said it's still worth adding, just put a comment at the top mentioning this risk.

> Quick and painless to launch an environment that is guaranteed to build that particular project.

I really should start using something like this. Just spent an hour messing with Gradle/JDK nonsense I don't even understand to get the app to build (isn't the point of Flutter to abstract away platform-specific concerns?!?).
